"Select kh.MAKHACHHANG, kh.NGAYLAP, kh.TENKHACHHANG, kh.TENCHURE, 
kh.TENCODAU, kh.DIACHI, kh.DIENTHOAI, kh.EMAIL, kh.NGAYTOCHUC, 
kh.SOLUONGBAN, kh.BANDUTRU,kh.TIENCOC,kh.BANDUTRU,
FROM KHACHHANGINFO kh
Where MAKHACHHANG =  "